### ISSUE TITLE
Error running docker-compose up -d

### ISSUE THREAD

**Issue by connorwang** [Monogramm/docker-taiga#51]
**Getting the following error while running docker-compose up -d for taiga 6.0**
```
WARNING: The DOCKERFILE_PATH variable is not set. Defaulting to a blank string.
WARNING: The IMAGE_NAME variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 466, in up
  File "compose/service.py", line 333, in ensure_image_exists
  File "compose/service.py", line 353, in image
  File "site-packages/docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[25669] Failed to execute script docker-compose
```

**Docker Version**
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Docker-compose Version**
```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by connorwang** [comment]
Also I noticed that the update.sh doesn't generate a test folder under the versions which will result in a docker build failure

**Comment by nuokh** [comment]
I encountered the same issue when trying to run ocker-compose up

**Comment by dbseoane** [comment]
I also have founded with this error when, by mistake, executed docker-compose up -d in the templates folder, instead of execute the docker-compose in the images/VARIANT/VERSION/ folder.
Hope this help somebody.
