### ISSUE TITLE
ModuleNotFoundError: No module named 'ldap3'

### ISSUE THREAD

**Issue by dbseoane** [Monogramm/docker-taiga#54]
**Describe the bug**
In a clean installation, after setup template/docker-compose.yml and template/.env files, the taiga_celery and taiga_back containers exits with this error.

**To Reproduce**

1. Edit the template/docker-compose.yml with custom parameters:
- LDAP enable, others disabled
- Custom ports
- Mail settings
- Production setup with monogramm/docker-taiga-* images, not building

2. Edit the template/.env with custom values
3. Execute update.sh script
4. Execute (image/variant/version/)docker-compose up -d

**Expected behavior**

All containers up and running. The ldap3 module should be included in the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/43339713/133287343-62d16974-3e7e-47aa-8181-11b0aedb89c9.png)
![image](https://user-images.githubusercontent.com/43339713/133289238-85b74f5f-4efa-4b83-9c0f-1535fd45a125.png)

**Docker:**

-   docker version                        
  Client:
   Version:           18.09.1
   API version:       1.39
   Go version:        go1.11.6
   Git commit:        4c52b90
   Built:             Sun, 21 Feb 2021 18:18:35 +0100
   OS/Arch:           linux/amd64
   Experimental:      false

- docker-compose version
  docker-compose version 1.21.0, build unknown
  docker-py version: 3.4.1
  CPython version: 3.7.3
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

-   Image docker-taiga-back:6.0-alpine

**Desktop:**

-   OS: Debian 10.10

**Additional context**
This is the full **container taiga_celery logs**:
```
[2021-09-14T17:16:20] Compiling messages and collecting static
Enabling Taiga emails...
Taiga events enabled
Taiga async mode enabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/compilemessages.py", line 64, in handle
    basedirs.extend(settings.LOCALE_PATHS)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/taiga-back/settings/config.py", line 12, in <module>
    from ldap3 import Tls
ModuleNotFoundError: No module named 'ldap3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/taiga-back/settings/config.py", line 12, in <module>
    from ldap3 import Tls
ModuleNotFoundError: No module named 'ldap3'
```

--------------------------------------------------------------------
And this is the full **taiga_back container logs**:
```
[2021-09-14T17:16:17] Running database check
Connecting to database:
dbname='taiga' user='taiga' host='taiga_db' port='5432' password='******'
Database does not appear to be setup.
[2021-09-14T17:16:18] Execute database migrations...
Enabling Taiga emails...
Taiga feedback enabled
Taiga events enabled
Taiga async mode enabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/taiga-back/settings/config.py", line 12, in <module>
    from ldap3 import Tls
ModuleNotFoundError: No module named 'ldap3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/taiga-back/settings/config.py", line 12, in <module>
    from ldap3 import Tls
ModuleNotFoundError: No module named 'ldap3'
```

It's seems like the module is not installed in the docker image.
Any help would be apreciated!

*Updated the steps to reproduce

**Comment by dbseoane** [comment]
I have solved the problem in question. I omit the step to docker-compose build when I did modifications in the files. After that the images had the module included.
But my question now is, why the images from monogram don't include the module? what is the difference between this images and the taiga.io ofical images?
Maybe the README should be a little more clear.
